pipeline {
    agent any 

    options {
        disableConcurrentBuilds()
    }

    environment {
        IMAGE_NAME = "hitfast/multibranch-app"
        GIT_USER = "social9009"
        GIT_EMAIL = "akshaysawant9009@gmail.com"
        IMAGE_TAG = ""
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm 
            }
        }

        stage('Build and Push Docker Image') {
            when { branch 'main' }
            steps {
                script {
                    env.IMAGE_TAG = "build-${env.BUILD_NUMBER}"
                }

                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds', 
                    usernameVariable: 'DOCKERHUB_USER', 
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {

                    sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                        echo \$DOCKER_PASSWORD | docker login -u \$DOCKERHUB_USER --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        docker logout
                    """
                }
            }
        }

        stage('Update Kubernetes Deployment') {
            when { branch 'main' }
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-creds', 
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )]) {

                        sh """
                            set -e
                            git config user.name "${GIT_USER}"
                            git config user.email "${GIT_EMAIL}"

                            git fetch origin
                            git checkout main
                            git reset --hard origin/main

                            sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" k8s/deploy.yaml

                            git add k8s/deploy.yaml

                            git diff --cached --quiet || git commit -m "Update Image to ${IMAGE_TAG}"

                            git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/social9009/multi-Branch-pipeline.git main
                        """
                    }
                }
            }
        }
    }
}

